CREATE TABLE Employees
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	FullName NVARCHAR(255) NOT NULL,
	PhoneNumber NVARCHAR(20) NOT NULL UNIQUE,
	Email NVARCHAR(50) NOT NULL UNIQUE,
	AdressId INT NOT NULL,
	EmployeeTypeId INT NOT NULL,
	FOREIGN KEY(AdressId) REFERENCES Adresses(Id), 
	FOREIGN KEY(EmployeeTypeId) REFERENCES EmployeeTypes(Id)
);